
modLoader = "javafml"

loaderVersion = "${loader_version_range}"

license = "${mod_license}"

[[mods]]

modId = "squadmc"

version = "${mod_version}"

displayName = "SquadMcVehicles"

authors = "Ivlla"



description = '''This a mod for SquadMC Server'''

[[dependencies.squadmc]] #optional
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

[[dependencies.squadmc]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies.squadmc]]
modId = "superbwarfare"
mandatory = true
versionRange = "[0.8.8,)"
ordering = "NONE"
side = "BOTH"
